=== indx96/epamtask_5/resources/planes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="plane" type="plane-type"/>
    <xs:element name="fighter" type="fighter-type" substitutionGroup="plane"/>
    <xs:element name="airliner" type="airliner-type" substitutionGroup="plane"/>

    <xs:element name="planes">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="plane" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="amount">
        <xs:restriction base="xs:double">
            <xs:minInclusive value="1.0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="plane-ID">
        <xs:restriction base="xs:ID">
            <xs:pattern value="[A-z]\d+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="engine-type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="reactive"/>
            <xs:enumeration value="propeller"/>
            <xs:enumeration value="solid"/>
            <xs:enumeration value="liquid"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="plane-type">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="length" type="amount"/>
            <xs:element name="height" type="amount"/>
            <xs:element name="wingspan" type="amount"/>
            <xs:element name="fly-range" type="amount"/>
            <xs:element name="tanke-size" type="amount"/>
        </xs:sequence>
        <xs:attribute name="id" type="plane-ID" use="required"/>
        <xs:attribute name="engine" type="engine-type" use="optional"/>
    </xs:complexType>

    <xs:complexType name="fighter-type">
        <xs:complexContent>
            <xs:extension base="plane-type">
                <xs:sequence>
                    <xs:element name="weapons">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="bombs" type="xs:positiveInteger"/>
                                <xs:element name="guns" type="xs:positiveInteger"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="airliner-type">
        <xs:complexContent>
            <xs:extension base="plane-type">
                <xs:sequence>
                    <xs:element name="crew-amount" type="xs:positiveInteger"/>
                    <xs:element name="passengers-amount" type="xs:positiveInteger"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>


</xs:schema>

=== indx96/epamtask_5/resources/planes.xml
<?xml version="1.0" encoding="UTF-8"?>

<planes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="planes.xsd">

    <plane id="d1" engine="reactive">
        <name>plane</name>
        <length>1</length>
        <height>3</height>
        <wingspan>1</wingspan>
        <fly-range>1000</fly-range>
        <tanke-size>100</tanke-size>
    </plane>

    <fighter id="b3" engine="liquid">
        <name>fighter</name>
        <length>4</length>
        <height>3</height>
        <wingspan>3</wingspan>
        <fly-range>1500</fly-range>
        <tanke-size>150</tanke-size>
        <weapons>
            <bombs>12</bombs>
            <guns>45</guns>
        </weapons>
    </fighter>

    <airliner id="c5">
        <name>airliner</name>
        <length>8</length>
        <height>4</height>
        <wingspan>10</wingspan>
        <fly-range>1200</fly-range>
        <tanke-size>200</tanke-size>
        <crew-amount>15</crew-amount>
        <passengers-amount>100</passengers-amount>
    </airliner>
</planes>
